---
Stack.Name: web-proxy
Stack.Description: Web Proxy using popular squid application

Stack.Template: 'templates/proxy.yml.j2'
Sts.Role: arn:aws:iam::610547539895:role/admin
Sts.Region: us-west-2

Stack.Inputs:
  ApplicationImageId: ami-57d9cd2e
  ApplicationInstanceType: t2.micro
  ApplicationKeyName: admin
  ApplicationDesiredCount: "1"
  ProxyImage: 610547539895.dkr.ecr.us-west-2.amazonaws.com/casecommons/squid
  ProxyImageTag: latest
  ProxyWhitelist: .demo.callowayart.org
  ProxyDisableWhitelist: "true"
  DockerNetworkMode: host

AWS::Logs::LogGroup:
  DeletionPolicy: Delete
