# STS role in the target AWS account to assume
Sts.Role: arn:aws:iam::610547539895:role/admin

# Trusted entities for the IAM admin role
# Here we trust the demo-users account
# Application settings
config_application_keyname: admin
config_application_instance_type: t2.micro
config_application_ami: ami-275ffe31
config_az_count: 3
config_log_deletion_policy: Delete

# Proxy settings
config_proxy_image: 610547539895.dkr.ecr.us-east-1.amazonaws.com
config_proxy_tag: latest
config_proxy_disable_whitelist: false
config_proxy_whitelist: .demo.callowayart.com
config_proxy_network_mode: host
